name: Christopher Kline
favicon: null
layout_spectrum: 0.9993
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c391ae'
    - '#dbc4d8'
    - '#923f61'
    - '#441c32'
    - '#c65d8c'
  brandStrength: 0.6875
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
