name: Christopher Kline
favicon: null
layout_spectrum: 0.695
typography_spectrum: 0.989
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c391ae'
    - '#dbc4d8'
    - '#923f61'
    - '#441c32'
    - '#c65d8c'
  brandStrength: 0.21321698976680636
  lightness: 0.3177028498612344
  saturation: 0.9730966326314956
  rhythmicContrast: 0.7828332229983062
purpose: []
